### Cadastrar estudante
POST http://localhost:3003/user
Content-Type: application/json

{
  "nome": "Felipe",
  "email": "felipe@gmail.com",
  "data_nasc": "22/02/1995",
  "turma_id": "001"
}

### Buscar estudante por nome

GET http://localhost:3003/user/Fernando

### Mudar estudante de turma
POST http://localhost:3003/user/mudar-turma
Content-Type: application/json

{
  "idEstudante": "1662735848809",
  "turma": "002"
}

###

GET http://localhost:3003/turmas

###

POST http://localhost:3003/turma
Content-Type: application/json

{
  "nome": "Full-stack",
  "modulo": "05"
}
  
###

POST http://localhost:3003/criar-docente
Content-Type: application/json

{
  "nome": "Benjamin",
  "email": "benjamin@gmail.com",
  "data_nasc": "14/09/1992",
  "turma_id": "002"

}

###

GET http://localhost:3003/buscar-docentes

###

POST http://localhost:3003/mudar-docentes
Content-Type: application/json

{
  "idDocente":"1662861630056",
  "turma":"001"
}