POST http://localhost:3003/user
Content-Type: application/json

{
  "nome": "Felipe",
  "email": "felipe@gmail.com",
  "data_nasc": "22/02/1995",
  "turma_id": "001"
}

###

GET http://localhost:3003/turmas

###

POST http://localhost:3003/turma
Content-Type: application/json

{
  "nome": "Full-stack",
  "modulo": "05"
}
  
###

POST http://localhost:3003/criar-docente
Content-Type: application/json

{
  "nome": "Benjamin",
  "email": "benjamin@gmail.com",
  "data_nasc": "14/09/1992",
  "turma_id": "002"

}